# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      # - id: check-json
      # 
      # NOTE: The standar 'check-json' doesn't support JSON
      # with comments.  More info: 
      #   https://github.com/pre-commit/pre-commit-hooks/issues/395
      #
      # - repo: https://gitlab.com/bmares/check-json5
      #   rev: v1.0.0
      #   hooks:
      #   - id: check-json5
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.4
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: '3.11'
        args: ["--profile", "black"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.285
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    # Ruff version.
    rev: v1.4.0
    hooks:
      - id: mypy
        additional_dependencies: ["django-stubs==4.2.1"]
