#
# Based on:
# https://gist.github.com/jcataluna/1dc2f31694a1c301ab34dac9ccb385ea
#
# Non-CI version
#   docker compose build
#   docker-compose config --images
#     --- PRINTS ---
#      moosedj_web
#      moosedj_nginx
#   docker save -o docker-images.tar $(docker-compose config | awk '{if ($1 == "image:") print $2;}')
name: Package moosedj Docker Compose Bundle

on:
  # pull_request:
  #   types: [opened, synchronize, reopened]
  push:
    branches:
      # This is a cheap trick to disable this Github Actions Workflow
      - docker-build-branch
      # - main
      # - develop
  
permissions:
  contents: read
  packages: read

jobs:
  package-offline-bundle:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: b-long
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Write docker images to disk
        run: |
          docker compose -f docker-compose.yaml pull --ignore-buildable
          docker compose -f docker-compose.yaml build
          docker save -o docker-images.tar $(docker-compose -f docker-compose.yaml config | awk '{if ($1 == "image:") print $2;}')

      - name: Tar (xz compress) Docker files
        run: tar cvf compressed-docker-images.tar.xz --use-compress-program='xz -1' docker-images.tar docker-compose.yaml
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compressed-docker-images
          path: compressed-docker-images.tar.xz
          retention-days: 1
